### ISSUE TITLE
Couleur police

### ISSUE THREAD

**Issue by fabienjuif** [aya-experience/aya-experience.github.io#2]
(je ne sais pas si vous voulez les remarques en anglais ou pas, n'hésitez pas à me dire si je dois changer).

Les couleurs des polices d'écritures ne sont pas bonnes je pense, il est très difficile de lire le texte (sur fond noir ou sur fond blanc). Je pense ne pas être le seul à voir ça.

GJ sinon ;)

**Comment by Swiip** [comment]
(pas forcément réfléchis à la question de la langue, partons sur du français pour le moment)

La contrepartie d'avoir des jolies fonds et une police fine c'est qu'on perd en lisibilité, c'est sur.

On traite la question au cas par cas, des endroits en particulier que tu trouves peu lisible ?

Il y a les blocs code et design qui sont déjà identifiés en tout cas, ils nécessiteraient un peu plus de travail...

**Comment by fabienjuif** [comment]
J'ai pris deux captures qui résume bien.
Mais c'est surtout dans les dessins qu'on retrouve souvent à gauche / droite de la page.
Si tu penses que ça vient de mon système n'hésite pas à me demander de faire des tests.
Je peux même essayer d'ajuster la couleur et te renvoyer le code/capture.

 - Google Chrome
 - Linux
 - Ecran rétina

![aya_1](https://cloud.githubusercontent.com/assets/17828231/19348678/67b160b8-914f-11e6-839c-1bff4f6e2d1c.png)
![aya_2](https://cloud.githubusercontent.com/assets/17828231/19348679/68cb7fa6-914f-11e6-8cce-abd2702a2463.png)

**Comment by Swiip** [comment]
Ouch, il y a un comportement bizarre, je n'ai pas ça : 
<img width="370" alt="capture d ecran 2016-10-13 a 14 19 07" src="https://cloud.githubusercontent.com/assets/475895/19348816/1262efd6-9150-11e6-9aef-e4c3baabfe5b.png">

**Comment by hgwood** [comment]
Pour info sous Windows 7, Chrome, non rétina

![image](https://cloud.githubusercontent.com/assets/1656170/19348988/0189d2f0-9151-11e6-8477-f2d471d81046.png)

![image](https://cloud.githubusercontent.com/assets/1656170/19349012/1d4c6890-9151-11e6-9abf-cbab39a48156.png)

**Comment by fabienjuif** [comment]
Sauf erreur de ma part, il y a pas de `font-family`.
Donc le site est très dépendant des OS/DE/WM.

Peut être qu'on peut essayer de définir un `font-family` ?
En plus un `font-weight: 100` ça me parrait vraiment léger !

**Comment by Swiip** [comment]
Ohoh...

Le site devrait être en Lato : https://github.com/aya-experience/aya-experience.github.io/blob/316d3cfda721482675aa6421326cc8515ee783a2/src/style/_global.scss

 Et la police en webfont comme sur le nouveau site corp, mais je vois pas la police chargée.

Si c'est ça, c'est un bète oublie...

**Comment by Swiip** [comment]
Flute, ça "devrait" marcher.

https://github.com/aya-experience/aya-experience.github.io/blob/dev/src/index.html#L11-L13

**Comment by fabienjuif** [comment]
Bon c'est surement moi qui avait pas les yeux en face des trous, mais j'ai bien la police effectivement. Le `font-family` est bien présent.
J'ai testé de mettre sans-serif et là je vois tout bien.
Donc je ne sais pas trop d'où ça vient :/

**Comment by FBerthelot** [comment]
Cette issue sera résolue fatalement dans la nouvelle version du site où le contraste sera meilleure avec un abandons des masks SVG qui a un comportement bizarre sur les différents navigateurs.
