### ISSUE TITLE
Page - Vision

### ISSUE THREAD

**Issue by JustineGaudin** [aya-experience/aya-experience.github.io#58]
Hello ! J'ai revu les slides de présentaiton d'AYA graphiquement (voir dans le drive)
[Ici](https://docs.google.com/presentation/d/1WGyEfXg71X6eWT9z4aB4QDxfc-u-2peptWvIspoRLy4/edit#slide=id.g2658ee1bfb_0_94) qui concordent avec la page Vision de l'APP AYA. D'ailleurs voici le SVG ci-joint du nouveau schéma (en zip car github ne prends pas les svg)

Bonne journée ! 😄 

[Assets_Plan de travail 1.svg.zip](https://github.com/aya-experience/aya-experience.github.io/files/1903393/Assets_Plan.de.travail.1.svg.zip)

**Comment by Madaoo** [comment]
En cours de réalisation, Merci !
